POLITIFACT = [{"district":1,"representative":"Matt Gaetz","TRUE":0,"mostly true":1,"half true":1,"mostly false":0,"FALSE":1,"pants on fire":0},
{"district":2,"representative":"Neal Dunn","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":3,"representative":"Ted Yoho","TRUE":1,"mostly true":0,"half true":0,"mostly false":1,"FALSE":1,"pants on fire":0},
{"district":4,"representative":"John Rutherford","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":5,"representative":"Al Lawson","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":6,"representative":"Ron DeSantis","TRUE":1,"mostly true":1,"half true":0,"mostly false":0,"FALSE":0,"pants on fire":0},
{"district":7,"representative":"Stephanie Murphy","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":8,"representative":"Bill Posey","TRUE":0,"mostly true":1,"half true":1,"mostly false":0,"FALSE":0,"pants on fire":0},
{"district":9,"representative":"Darren Soto","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":10,"representative":"Val Demings","TRUE":0,"mostly true":0,"half true":0,"mostly false":1,"FALSE":0,"pants on fire":0},
{"district":11,"representative":"Daniel Webster","TRUE":0,"mostly true":1,"half true":0,"mostly false":0,"FALSE":0,"pants on fire":0},
{"district":12,"representative":"Gus Bilirakis","TRUE":0,"mostly true":1,"half true":0,"mostly false":1,"FALSE":1,"pants on fire":0},
{"district":13,"representative":"Charlie Crist","TRUE":15,"mostly true":19,"half true":20,"mostly false":15,"FALSE":9,"pants on fire":2},
{"district":14,"representative":"Kathy Castor","TRUE":1,"mostly true":0,"half true":1,"mostly false":0,"FALSE":0,"pants on fire":0},
{"district":15,"representative":"Dennis Ross","TRUE":1,"mostly true":0,"half true":0,"mostly false":0,"FALSE":0,"pants on fire":0},
{"district":16,"representative":"Vern Buchanan","TRUE":2,"mostly true":0,"half true":1,"mostly false":1,"FALSE":1,"pants on fire":0},
{"district":17,"representative":"Thomas Rooney","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":18,"representative":"Brian Mast","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":19,"representative":"Francis Rooney","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":20,"representative":"Alcee Hastings","TRUE":0,"mostly true":0,"half true":1,"mostly false":1,"FALSE":0,"pants on fire":2},
{"district":21,"representative":"Lois Frankel","TRUE":0,"mostly true":0,"half true":0,"mostly false":2,"FALSE":0,"pants on fire":1},
{"district":22,"representative":"Theodore Deutch","TRUE":None,"mostly true":None,"half true":None,"mostly false":None,"FALSE":None,"pants on fire":None},
{"district":23,"representative":"Debbie Wasserman Schultz","TRUE":5,"mostly true":15,"half true":8,"mostly false":7,"FALSE":9,"pants on fire":3},
{"district":24,"representative":"Frederica Wilson","TRUE":1,"mostly true":1,"half true":1,"mostly false":1,"FALSE":0,"pants on fire":0},
{"district":25,"representative":"Mario Diaz-Balart","TRUE":1,"mostly true":1,"half true":0,"mostly false":0,"FALSE":1,"pants on fire":0},
{"district":26,"representative":"Carlos Curbelo","TRUE":1,"mostly true":1,"half true":0,"mostly false":0,"FALSE":1,"pants on fire":0},
{"district":27,"representative":"Ileana Ros-Lehtinen","TRUE":1,"mostly true":0,"half true":1,"mostly false":0,"FALSE":0,"pants on fire":0}];
