REPS = [{"district":1,"name":"Matt Gaetz","party":"Republican"},
{"district":2,"name":"Neal Dunn","party":"Republican"},
{"district":3,"name":"Ted Yoho","party":"Republican"},
{"district":4,"name":"John Rutherford","party":"Republican"},
{"district":5,"name":"Al Lawson","party":"Democrat"},
{"district":6,"name":"Ron DeSantis","party":"Republican"},
{"district":7,"name":"Stephanie Murphy","party":"Democrat"},
{"district":8,"name":"Bill Posey","party":"Republican"},
{"district":9,"name":"Darren Soto","party":"Democrat"},
{"district":10,"name":"Val Demings","party":"Democrat"},
{"district":11,"name":"Daniel Webster","party":"Republican"},
{"district":12,"name":"Gus Bilirakis","party":"Republican"},
{"district":13,"name":"Charlie Crist","party":"Democrat"},
{"district":14,"name":"Kathy Castor","party":"Democrat"},
{"district":15,"name":"Dennis Ross","party":"Republican"},
{"district":16,"name":"Vern Buchanan","party":"Republican"},
{"district":17,"name":"Thomas Rooney","party":"Republican"},
{"district":18,"name":"Brian Mast","party":"Republican"},
{"district":19,"name":"Francis Rooney","party":"Republican"},
{"district":20,"name":"Alcee Hastings","party":"Democrat"},
{"district":21,"name":"Lois Frankel","party":"Democrat"},
{"district":22,"name":"Theodore Deutch","party":"Democrat"},
{"district":23,"name":"Debbie Wasserman Schultz","party":"Democrat"},
{"district":24,"name":"Frederica Wilson","party":"Democrat"},
{"district":25,"name":"Mario Diaz-Balart","party":"Republican"},
{"district":26,"name":"Carlos Curbelo","party":"Republican"},
{"district":27,"name":"Ileana Ros-Lehtinen","party":"Republican"}];
