REPS = [{"id":26299720,"district":1,"name":"Matt Gaetz","party":"Republican"},
{"id":58891899,"district":2,"name":"Neal Dunn","party":"Republican"},
{"id":48831783,"district":3,"name":"Ted Yoho","party":"Republican"},
{"id":34528073,"district":4,"name":"John Rutherford","party":"Republican"},
{"id":77971227,"district":5,"name":"Al Lawson","party":"Democrat"},
{"id":87899592,"district":6,"name":"Ron DeSantis","party":"Republican"},
{"id":89606208,"district":7,"name":"Stephanie Murphy","party":"Democrat"},
{"id":55484810,"district":8,"name":"Bill Posey","party":"Republican"},
{"id":87557769,"district":9,"name":"Darren Soto","party":"Democrat"},
{"id":23833011,"district":10,"name":"Val Demings","party":"Democrat"},
{"id":39146845,"district":11,"name":"Daniel Webster","party":"Republican"},
{"id":64540623,"district":12,"name":"Gus Bilirakis","party":"Republican"},
{"id":72562239,"district":13,"name":"Charlie Crist","party":"Democrat"},
{"id":52433202,"district":14,"name":"Kathy Castor","party":"Democrat"},
{"id":68478499,"district":15,"name":"Dennis Ross","party":"Republican"},
{"id":77887485,"district":16,"name":"Vern Buchanan","party":"Republican"},
{"id":96231639,"district":17,"name":"Thomas Rooney","party":"Republican"},
{"id":53613908,"district":18,"name":"Brian Mast","party":"Republican"},
{"id":48604700,"district":19,"name":"Francis Rooney","party":"Republican"},
{"id":43095669,"district":20,"name":"Alcee Hastings","party":"Democrat"},
{"id":99785689,"district":21,"name":"Lois Frankel","party":"Democrat"},
{"id":70937893,"district":22,"name":"Theodore Deutch","party":"Democrat"},
{"id":45716456,"district":23,"name":"Debbie Wasserman Schultz","party":"Democrat"},
{"id":82256502,"district":24,"name":"Frederica Wilson","party":"Democrat"},
{"id":75809397,"district":25,"name":"Mario Diaz-Balart","party":"Republican"},
{"id":46485491,"district":26,"name":"Carlos Curbelo","party":"Republican"},
{"id":77321909,"district":27,"name":"Ileana Ros-Lehtinen","party":"Republican"}];

REPS2 = [{"district":1,"name":"Matt Gaetz","party":"Republican"},
{"district":2,"name":"Neal Dunn","party":"Republican"},
{"district":3,"name":"Ted Yoho","party":"Republican"},
{"district":4,"name":"John Rutherford","party":"Republican"},
{"district":5,"name":"Al Lawson","party":"Democrat"},
{"district":6,"name":"Ron DeSantis","party":"Republican"},
{"district":7,"name":"Stephanie Murphy","party":"Democrat"},
{"district":8,"name":"Bill Posey","party":"Republican"},
{"district":9,"name":"Darren Soto","party":"Democrat"},
{"district":10,"name":"Val Demings","party":"Democrat"},
{"district":11,"name":"Daniel Webster","party":"Republican"},
{"district":12,"name":"Gus Bilirakis","party":"Republican"},
{"district":13,"name":"Charlie Crist","party":"Democrat"},
{"district":14,"name":"Kathy Castor","party":"Democrat"},
{"district":15,"name":"Dennis Ross","party":"Republican"},
{"district":16,"name":"Vern Buchanan","party":"Republican"},
{"district":17,"name":"Thomas Rooney","party":"Republican"},
{"district":18,"name":"Brian Mast","party":"Republican"},
{"district":19,"name":"Francis Rooney","party":"Republican"},
{"district":20,"name":"Alcee Hastings","party":"Democrat"},
{"district":21,"name":"Lois Frankel","party":"Democrat"},
{"district":22,"name":"Theodore Deutch","party":"Democrat"},
{"district":23,"name":"Debbie Wasserman Schultz","party":"Democrat"},
{"district":24,"name":"Frederica Wilson","party":"Democrat"},
{"district":25,"name":"Mario Diaz-Balart","party":"Republican"},
{"district":26,"name":"Carlos Curbelo","party":"Republican"},
{"district":27,"name":"Ileana Ros-Lehtinen","party":"Republican"}];
